### PR TITLE
Tests updated for v0.8.2

### LINKED ISSUE #146: Github test debts
Current debts, both blocked by 3rd party issue resolution:

- [x] bls, one case (blocked by https://github.com/ethereum/eth2.0-spec-tests/issues/3 )
- [x] spec configs in tests repository (blocked by https://github.com/ethereum/eth2.0-spec-tests/issues/1)

Please, follow updates and resolve when possible

### PR DESCRIPTION
**Pull request by zilm13**
TODO:
- [x] tests repository caching on CI
- [x] `ssz_generic` + `ssz_static` tests
- [x] `.ssz` support of data

Already resolves #146

### CODE REVIEW

**Comment by zilm13** [comment]
.ssz support of data added

**Comment by zilm13** [comment]
`ssz_static` tests added

**Comment by zilm13** [comment]
all ssz generic tests added

**Review by mkalinin — APPROVED** [review]
Tremendous work! 👍 Nothing to add, let's merge it when CI tests pass!

**Pull request merged**
