### PR TITLE
Make ordered iteration of tasks scheduled to the same time

### PR DESCRIPTION
**Pull request by Nashatyrev**
Fix non-deterministic behavior of `ControlledScheduler`

### CODE REVIEW

**Review by ericsson49 — CHANGES_REQUESTED** [review]
The new version is a bit less safe.
In the previous version, same task cannot be added twice, since TreeMultimap will ignore it.
However, in the new version, a new instance of OrderedTask will be added, having distinct getOrder() result and thus, it will be different from the TreeMultimap point of view.
It doesn't look like terribly wrong behavior, but it's different from the previous version.

If it's okay, I would also note, that such a doubly added task, won't be removed by a single cancelTask call. This is kinda consistent (added twice then it should be removed twice), but looks unsafe. Previously, some code can call addTask(t) twice for some reason, and a single cancelTask will remove it. But in the new version, there will be a problem.

**Comment by Nashatyrev** [comment]
@ericsson49 adding the same task twice is pretty strange intention. Added javadoc to prevent this :)

**Comment by Nashatyrev** [comment]
The most proper way would be to override `TreeMultimap.createCollection()` to return `LinkedHashSet` instance but it's package private :(

**Review by zilm13 — APPROVED** [review]
LGTM

**Review by ericsson49 — APPROVED** [review]

**Pull request merged**
